apiVersion: apps/v1
kind: Deployment
metadata:
  name: tftapples-deployment
  labels:
    app: tftapples
spec:
  replicas: 6
  selector:
    matchLabels:
      app: tftapples
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tftapples
    spec:
      containers:
      - name: tftapples
        image: limpylimbs/tftapples:36
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: RIOT_API_KEY
          valueFrom:
            secretKeyRef: 
              name: tftapples-secrets
              key: riot_api_key
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: tftapples-service
spec:
  selector:
    app: tftapples
  ports:
  - nodePort: 32720
    port: 80
    protocol: TCP
    targetPort: 80
  type: LoadBalancer